# Generated by Django 5.2.6 on 2025-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='continent',
            field=models.CharField(blank=True, choices=[('Africa', 'Африка'), ('Europe', 'Европа'), ('North America', 'Северная Америка'), ('South America', 'Южная Америка'), ('Asia', 'Азия'), ('Australia', 'Австралия'), ('Antarctica', 'Антарктида')], max_length=47, verbose_name='Континент'),
        ),
    ]
