# Generated by Django 5.2.6 on 2025-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_tour_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего мест'),
        ),
    ]
